_BlaineBattleText::
	text "Herrhem!..."
	line "cough...yack!"
	para "My apologies there"
	line "young one!"
	para "This old throat"
	line "needs a cleanin'!"
	para "Do I have you"
	line "stumped though on"
	cont "this SCI Quiz"
	cont "Question?"
	para "Yes, it's TRUE that"
	line "OBSERVATIONS can"
	cont "become"
	para "Scientific LAWS"
	line "if observed"
	cont "to occur time and"
	cont "time again with"
	para "no change in"
	line "results!"
	para "However, when it"
	line "comes to the"
	cont "NATURE of"
	cont "particles,"
	para "there is MORE THAN"
	line "MEETS THE EYE!"
	para "At a QUANTUM Level,"
	line "matter exhibits"
	cont "BOTH particle and"
	para "WAVE-like"
	line "properties!"
	para "Ahem...you look"
	line "even more lost!"
	para "Think about it like"
	line "this; at QUANTUM"
	cont "scale things can"
	para "be DEAD and ALIVE"
	line "simultaneously!"
	para "Still confused???"
	para "Well maybe a little"
	line "SPAR will clear"
	cont "your young"
	cont "SCIENTIFIC MIND!"
	done

_BlaineEndBattleText::
	text "My word!"
	line "This one could"
	cont "be special!"

	para "You have earned"
	line "the METHODBADGE!@@"

_BlaineFireBlastText::
	text "Oh...before I"
	line "forget!"
	para "I think you've"
	line "more than earned"
	cont "a tour of my lab!"
	para "It's just up"
	line "those stairs and"
	cont "to the right!"
	para "Why don't you"
	line "meet me up there!"
	done

_BlaineBadgeText::
	text "Hah! That's"
	line "the SCI spirit!"
	para "Your SCIENTIFIC"
	line "MIND burns bright"
	cont "young one!"
	para "Don't fret over"
	line "that last"
	cont "question!"
	para "The purpose of it"
	line "was to stress the"
	cont "fact that in"
	para "SCIENCE things"
	line "can change fast"
	cont "whenever new DATA"
	cont "is found!"
	para "SCIENCE can be"
	line "THUNDEROUSLY"
	cont "UNPREDICTABLE,"
	cont "if you will!"
	para "Having an OPEN"
	line "mind and thinking"
	cont "OUTSIDE the box"
	para "is thus how great"
	line "SCIENTISTS break"
	cont "through mental"
	para "barriers to SOLVE"
	line "our universe's"
	cont "greatest"
	cont "MYSTERIES!"
	para "Now then..."
	para "The METHODBADGE"
	line "heightens the"
	cont "latent POWER"
	cont "of your #MON!"
	para "But it will also"
	line "let you use THIS"
	cont "outside of battle!"
	done

_ReceivedTM38Text::
	text "<PLAYER> received"
	line "@"
	TX_RAM wcf4b
	text "!@@"

_TM38ExplanationText::
	text ""

	para "HM03 contains"
	line "SURF!"

	para "Teach it to water-"
	line "type #MON,"
	para "like the ones you"
	line "find FISHING,"

	para "and use it to"
	line "CONTINUE on your"
	cont "SCIENTIFIC QUEST!"
	done

_TM38NoRoomText::
	text "Make room for my"
	line "gift!"
	done

_CinnabarGymText_75994::
	text "My glasses! I"
	line "need them to see"
	cont "what on Earth"
	para "the SCI QUIZ"
	line "QUESTION was..!"
	para "FOUND 'EM!"
	para "Sniffle..."
	para "Asking a QUESTION"
	line "after making an"
	cont "OBSERVATION is"
	para "the 1st part of"
	line "SCIENTIFIC METHOD!"
	cont "was the QUESTION!"
	para "Yes...this is true!"
	line "The first part of"
	cont "SCIENTIFIC METHOD"
	para "is making"
	line "OBSERVATIONS and"
	cont "then using your"
	para "RESEARCH and"
	line "INQUIRY skills to"
	cont "ask a testable"
	para "QUESTION!"
	done

_CinnabarGymText_75999::
	text "My"
	line "glasses!"
	prompt

_CinnabarGymText_7599e::
	text "Sniffle..."
	para "The number of"
	line "steps in the"
	cont "SCIENTIFIC METHOD"
	para "varies, but it"
	line "always starts"
	cont "with making"
	para "OBSERVATIONS,"
	line "which leads to"
	cont "RESEARCH that can"
	para "help you form a"
	line "QUESTION to sync"
	cont "with a PROBLEM!"
	done
	
_CinnabarGymText_759fe::
	text "Are you like, dumb"
	line "or something?"
	para "The Sci Quiz"
	line "QUESTION was;"
	para "Properly designed"
	line "science"
	cont "experiments have"
	para "AT LEAST 2 main"
	line "types of"
	cont "variables?!"
	para "This is WRONG!"
	para "There are at least"
	line "THREE types of"
	cont "variables in ANY"
	para "SCI EXPERIMENT!"
	done

_CinnabarGymText_75a03::
	text "Rude"
	line "boy!"
	para "Talk to me again"
	line "and you will"
	cont "regret it!"
	prompt

_CinnabarGymText_75a08::
	para "meltEveryone knows that"
	line "EVERY science"
	cont "experiment MUST"
	para "have at least 3"
	line "types of variables!"
	para "These variables are"
	line "the CONTROL Variable"
	cont "which you DO NOT"
	para "change. It is held"
	line "CONSTANT!"
	para "You also have the 2"
	line "experimental variables"
	cont "aka the DEPENDENT"
	para "and INDEPENDENT"
	line "variables!"
	para "When GRAPHING your"
	line "DATA be sure to"
	cont "PLOT the"
	para "DEPENDENT variable"
	line "on the Y-AXIS,"
	cont "and the"
	para "INDEPENDENT"
	line "variable on the"
	cont "X-AXIS!"
	done

_CinnabarGymText_759c9::
	text "My big bro has"
	line "been a student"
	cont "of both G AND"
	para "MR. FLOYD!"
	para "He taught me"
	line "the answer to"
	cont "this SCI QUIZ"
	para "QUESTION;"
	para "The THIRD part of"
	line "SCIENTIFIC METHOD"
	cont "requires you to"
	para "ANALYZE the data"
	line "you collected in"
	cont "your EXPERIMENT?!"
	para "How can you ANALYZE"
	line "data before you"
	cont "DESIGN 'n CONDUCT"
	para "an experiement to"
	line "let you COLLECT"
	cont "DATA?!"
	para "That is the correct"
	line "THIRD part of the"
	cont "SCIENTIFIC METHOD!"
	done

_CinnabarGymText_759ce::
	text "Waah!"
	line "Big bro! Help!"
	prompt

_CinnabarGymText_759d3::
	text "When desining your"
	line "EXPERIMENT make"
	cont "sure to clearly"
	para "WRITE out all of"
	line "the steps aka"
	cont "PROCEDURES while"
	para "also making a"
	line "list of MATERIALS"
	cont "that you'd need!"
	done
	
_CinnabarGymText_7595f::
	text "Girls can science"
	line "too ya know, so"
	cont "listen up!" 
	para "The QUESTION was;"
	para "Making a THEORY"
	line "aka an EDUCATED"
	cont "GUESS as to what"
	para "the answer is"
	line "to your question"
	cont "is the SECOND"
	para "part of the"
	line "SCIENTIFIC METHOD!"
	para "It's obviously"
	line "supposed to be"
	cont "that making a"
	para "HYPOTHESIS"
	line "aka an EDUCATED"
	cont "GUESS"
	para "is the second"
	line "part of the"
	para "SCIENTIFIC METHOD!"
	done

_CinnabarGymText_75964::
	text "How did I"
	line "not PREDICT this!"
	prompt

_CinnabarGymText_75969::
	text "A HYPOTHESIS is"
	line "just a PREDICTION,"
	cont "an EDUCATED GUESS"
	para "as to what you"
	line "THINK is going to"
	cont "happen."
	para "I like to write"
	line "mine as IF-THEN"
	cont "statements when"
	para "I SCIENCE!"
	done

_CinnabarGymText_75a33::
	text "Lil Bro! Is this"
	line "the clown that"
	cont "was botherin' you?"
	para "He can't even"
	line "answer a simple"
	cont "question right!"
	para "Mothball mouth"
	line "over here was"
	cont "asked;"
	para "The DEPENDENT"
	line "variable is what"
	cont "you CHANGE in an"
	para "experiment to"
	line "produce a RESULT!"
	para "Yo scrunch-face!"
	para "It's the"
	line "INDEPENDENT"
	cont "variable that"
	para "you CHANGE to"
	line "produce a resultant"
	cont "CHANGE in your"
	para "DEPENDENT VARIABLE!"
	done

_CinnabarGymText_75a38::
	text "What"
	line "the J?!"
	prompt

_CinnabarGymText_75a3d::
	text "The DEPENDENT"
	line "variable DEPENDS"
	cont "on the INDEPENDENT"
	para "so in a science"
	line "EXPERIMENT you"
	cont "only CHANGE the"
	para "INDEPENDENT"
	line "VARIABLE!"
	done

_CinnabarGymText_75a68::
	text "Why hello there!"
	para "As you move"
	line "ahead in your"
	cont "study of SCIENCE"
	para "you'll find that"
	line "us ladies are"
	cont "far more involved"
	para "with SCIENCE than"
	line "we're given credit"
	cont "for!"
	para "Now then...your"
	line "question was;"
	para "TOOLS used to"
	line "collect DATA are"
	cont "SYSTEMS and after"
	para "you use one you"
	line "must make sure"
	cont "that it is"
	para "CALIBRATED?!"
	para "This is CLOSE!"
	para "But it's off"
	line "just a bit!"
	para "We CALIBRATE"
	line "scientific"
	cont "tools and"
	para "INSTRUMENTS by"
	line "ZERO-ING them"
	cont "out to match a"
	para "standard value!"
	para "This must be"
	line "done BEFORE you"
	cont "use one though!"
	done

_CinnabarGymText_75a6d::
	text "Zero-ed"
	line "out!"
	prompt

_CinnabarGymText_75a72::
	text "Scientific TOOLS,"
	line "such as a MASS"
	cont "measuring BALANCE"
	para "or a WEIGHT"
	line "measuring SCALE,"
	cont "are still"
	para "SYSTEMS since they"
	line "are made of many"
	cont "SMALL parts that"
	para "work together to"
	line "perform a task!"
	para "Systems have 4"
	line "factors that go"
	cont "into their"
	cont "operation."
	para "INPUT, PROCESS,"
	line "OUTPUT, and..."
	cont "FEEDBACK!"
	done

_CinnabarGymText_75a9d::
	text "I'm G's top"
	line "teaching aide!"
	para "He hired me"
	line "after his last"
	cont "TA vanished..."
	para "mainly because he"
	line "thought we were" 
	cont "alike!"
	para "Anywho, you"
	line "were asked;"
	para "The CONCLUSION"
	line "involves analyzing"
	cont "graphed/tabulated"
	para "DATA to ACCEPT or"
	line "REJECT your"
	para "HYPOTHESIS?!"
	para "You're nearing the"
	line "CONCLUSION of our"
	cont "GYM since that"
	para "was CORRECT!"
	done

_CinnabarGymText_75aa2::
	text "I guess"
	line "I'm not INTELLIGENT"
	cont "enough yet!"
	prompt

_CinnabarGymText_75aa7::
	text "The FINAL step"
	line "of the"
	cont "SCIENTIFIC METHOD"
	para "is to step back"
	line "and LOOK at your"
	cont "DATA and RESULTS"
	para "to then CONCLUDE,"
	line "FIGURE OUT,INFER,"
	cont "or ANSWER what"
	para "your EXPERIMENT"
	line "was about!"
	para "You can then"
	line "ACCEPT or REJECT"
	cont "your HYPOTHESIS!"
	para "Good scientists"
	line "also wrap things"
	cont "up by WRITING a"
	para "NON-BIASED lab"
	line "REPORT sharing"
	cont "their FINDINGS"
	para "while also sharing"
	line "things they would"
	cont "CHANGE or ADD if"
	para "they were to alter"
	line "their initial"
	cont "HYPOTHESIS and"
	para "RE-DO their"
	line "EXPERIMENT!"
	done
	
_CinnabarGymText_75a9dd::
	text "Girls can science"
	line "too ya know, so"
	cont "listen up!" 
	para "The QUESTION was;"
	para "Making a THEORY"
	line "aka an EDUCATED"
	cont "GUESS as to what"
	para "the answer is"
	line "to your question"
	cont "is the SECOND"
	para "part of the"
	line "SCIENTIFIC METHOD!"
	para "It's obviously"
	line "supposed to be"
	cont "that making a"
	para "HYPOTHESIS"
	line "aka an EDUCATED"
	cont "GUESS"
	para "is the second"
	line "part of the"
	para "SCIENTIFIC METHOD!"
	done

_CinnabarGymText_75aa2d::
	text "How did I"
	line "not PREDICT this!"
	prompt

_CinnabarGymText_75aa7d::
	text "A HYPOTHESIS is"
	line "just a PREDICTION,"
	cont "or EDUCATED GUESS"
	para "as to what you"
	line "THINK is going to"
	cont "happen!"
	para "I like to write"
	line "mine as IF-THEN"
	cont "statements when"
	cont "I DO SCIENCE!"
	done
	
_CinnabarGymText_75a9ddg::
	text "Fire is weak"
	line "against H2O!"
	done

_CinnabarGymText_75aa2dg::
	text "Oh!"
	line "Snuffed out!"
	prompt

_CinnabarGymText_75aa7dg::
	text "Everyone knows that"
	line "EVERY science"
	cont "experiment MUST"
	para "have at least 3"
	line "types of"
	cont "variables!"
	para "These variables"
	line "are the CONTROL"
	cont "Variable, which"
	cont "you DO NOT change."
	para "It is held"
	line "CONSTANT!"
	para "You also have the"
	line "2 experimental"
	cont "variables,"
	para "aka the DEPENDENT"
	line "and INDEPENDENT"
	cont "variables!"
	para "When GRAPHING your"
	line "DATA be sure to"
	cont "PLOT the"
	para "DEPENDENT variable"
	line "on the Y-AXIS,"
	cont "and the"
	para "INDEPENDENT"
	line "variable on the"
	cont "X-AXIS!"
	done

_CinnabarGymText_75ac2::
	text "Yo! Chef in"
	line "making!"

	para "You're in G's"
	line "house now!"
	
	para "He's a man of"
	line "method, and by"
	cont "that I mean"
	para "SCIENTIFIC"
	line "METHOD!"

	para "He specializes in"
	line "NORMAL Types, so"

	para "you better take"
	line "something BLAND"
	cont "to eat during the" 
	para "PEER REVIEW!"
	done

_CinnabarGymText_75ac7::
	text "<PLAYER>! You beat"
	line "G?!"
	para "Maybe you really"
	line "are a CHEF in"
	cont "MAKING!"
	done
	
_CinnabarGymText12::
	text "<PLAYER>! You beat"
	line "that fire brandddd!"
	done
