_LanceBeforeBattleText::
	text "Well well well..."
	para "If it isn't my"
	line "former student,"
	cont "here to CHALLENGE"
	cont "his old teacher."
	
	para "I thought I had"
	line "taught you well"
	cont "enough to know"
	cont "that you'd NEVER"
	cont "be better than I."
	
	para "Oh well...ya know,"
	line "they say I'm not"
	cont "REAL, but BELIEVE"
	para "me when I say that"
	line "I'm REAL ENOUGH to"
	cont "FINISH you off..."
	
	para "So then...CHEF!"
	para "Not even the UNITS"
	line "can save you now!"
	para "And FYI..."
	para "This is NO"
	line "RED HERRING!?!?!"
	done

_LanceEndBattleText::
	text "The units!"
	para "They didn't guide"
	line "me!"
	prompt

_LanceAfterBattleText1::
	text "I...I don't"
	line "believe it..."
	para "I...I WON'T"
	line "believe it!"
	para "I CANNOT lose!"
	para "I WILL NOT lose!"
	para "I am AKILA!"
	para "My mere name means"
	line "INTELLIGENT!"
	para "I cannot face"
	line "DEFEAT!"
	para "<PLAYER>!"
	para "You may have won"
	line "this battle, but"
	cont "my brain WILL win"
	cont "THE WAR!"
	para "You can search my"
	line "lab for EONS"
	cont "if you'd like, but"
	para "you'll NEVER"
	line "figure out how to"
	cont "FIND what you're"
	cont "after!"
	para "Go ahead and make"
	line "that fact a"
	cont "SCIENTIFIC"
	cont "LAW!"
	done