_OakSpeechText1::
	text "STUDENTS!!!"
	para "I, Mr. Floyd,"
	line "need your help!"
	para "The past few"
	line "months I've been"
	cont "working on a top"
	cont "secret project."
	para "The goal?"
	para "Well, that's "
	line "simple..."
	para "Students are"
	line "always asking me"
	cont "why I became a"
	cont "teacher and how I"
	para "earned my title"
	line "of The Chef."
	para "I thus wanted to"
	line "create a digital"
	cont "world to not only"
	para "share and model"
	line "my scientific"
	cont "story with the"
	cont "world, but to"
	para "also help cyber"
	line "students learn"
	cont "about SCIENCE!"
	prompt

_OakSpeechText2A::
	text "I thus chose to"
	line "base my virtual"
	cont "realm on one of"
	para "the most popular"
	line "games of all time;"
	para "#MON!@@"

_OakSpeechText2B::
	text $51,"However, despite"
	line "all going well at"
	cont "first things took"
	cont "an unxpected turn,"
	para "when my own former"
	line "teacher turned"
	cont "enemy trapped me"
	para "within the game"
	line "itself!!!"
	prompt

_IntroducePlayerText::
	text "SO!"
    para "I thus need"
	line "YOU, cyberstudent"
	cont "scientists, to"
	para "FIGURE OUT how"
	line "the J to GET ME"
	cont "OUT OF HERE!"
	para "So then, just"
	line "what is your"
	cont "name?"
	prompt

_IntroduceRivalText::
	text "Oh, and before I"
	line "forget..."
	para "That former teacher"
	line "of mine that I"
	cont "mentioned before?"
	para "Ya know...the"
	line "one who turned"
	cont "evil and trapped"
	cont "me in here?"
	para "He has a new"
	line "student of his"
	cont "own..."
	para "One who wants to"
	line "make sure that I"
	cont "NEVER get out of"
	cont "here..."
	para "He's one of only"
	line "a handful of"
	cont "characters in the"
	cont "game that'll know"
	cont "who you are, so"
	para "I'm also giving"
	line "you a Chef Hat"
	cont "to wear as a"
	cont "disguise."
	para "What was their"
	line "name again?"
	prompt

_OakSpeechText3::
	text "<PLAYER>!"

	para "Only YOU and"
	line "your SCIENTIFIC"
	cont "MIND can save me!"
	para "I believe that"
	line "YOU have what it"
	cont "takes, so BELIEVE"
	para "in yourself and"
	line "step into the"
	cont "digital world..."
	para "If you dare..."
	done
